[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1"
path = "1/main.rs"
test = false

[[bin]]
name = "2"
path = "2/main.rs"
test = false

[[bin]]
name = "3"
path = "3/main.rs"
test = false

[dependencies]
regex = "1.11.1"
